services:
  db:
    image: postgres:latest
    volumes:
      - risque-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=risque_development
      - POSTGRES_USER=risque
      - POSTGRES_PASSWORD=password
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/risque:cached
      - risque-bundle:/risque/vendor/bundle
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.
    network_mode: service:db # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=risque_development
      - BUNDLE_PATH=/risque/vendor/bundle
      - POSTGRES_USER=risque
      - POSTGRES_PASSWORD=password

volumes:
  risque-db:
    external: true
  risque-bundle:
    external: true