# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

def threat_sources
  ThreatSource.create(category: 'Adversarial', description: 'Individuals, groups, organizations, or states that seek to exploit the organization’s dependence on cyber resources (i.e., information in electronic form, information and communications technologies, and the communications and information-handling capabilities provided by those technologies).', is_adversarial: true)
  ThreatSource.create(category: 'Accidental', description: 'Erroneous actions taken by individuals in the course of executing their everyday responsibilities.', is_adversarial: false)
  ThreatSource.create(category: 'Structural', description: 'Failures of equipment, environmental controls, or software due to aging, resource depletion, or other circumstances which exceed expected operating parameters', is_adversarial: false)
  ThreatSource.create(category: 'Environmental', description: 'Natural disasters and failures of critical infrastructures on which the organization depends, but which are outside the control of the organization.
  Note: Natural and man-made disasters can also be characterized in terms of their severity and/or duration. However, because the threat source and the threat event are strongly identified, severity and duration can be included in the description of the threat event (e.g., Category 5 hurricane causes extensive damage to the facilities housing mission-critical systems, making those systems unavailable for three weeks).', is_adversarial: false)
end

def adversarial_threat_source_capabilities
  AdversarialThreatSourceCapability.create(qualitative: "Very High", quantitative: 10, description: "The adversary has a very sophisticated level of expertise, is well-resourced, and can generate opportunities to support multiple successful, continuous, and coordinated attacks.")
  AdversarialThreatSourceCapability.create(qualitative: "High", quantitative: 8, description: "The adversary has a sophisticated level of expertise, with significant resources and opportunities to support multiple successful coordinated attacks.")
  AdversarialThreatSourceCapability.create(qualitative: "Moderate", quantitative: 5, description: "The adversary has moderate resources, expertise, and opportunities to support multiple successful attacks.")
  AdversarialThreatSourceCapability.create(qualitative: "Low", quantitative: 2, description: "The adversary has limited resources, expertise, and opportunities to support a successful attack.")
  AdversarialThreatSourceCapability.create(qualitative: "Very Low", quantitative: 0, description: "The adversary has very limited resources, expertise, and opportunities to support a successful attack.")
end

def adversarial_threat_source_intents
  AdversarialThreatSourceIntent.create(qualitative: "Very High", quantitative: 10, description: "The adversary seeks to undermine, severely impede, or destroy a core mission or business function, program, or enterprise by exploiting a presence in the organization’s information systems or infrastructure. The adversary is concerned about disclosure of tradecraft only to the extent that it would impede its ability to complete stated goals.")
  AdversarialThreatSourceIntent.create(qualitative: "High", quantitative: 8, description: "The adversary seeks to undermine/impede critical aspects of a core mission or business function, program, or enterprise, or place itself in a position to do so in the future, by maintaining a presence in the organization’s information systems or infrastructure. The adversary is very concerned about minimizing attack detection/disclosure of tradecraft, particularly while preparing for future attacks.")
  AdversarialThreatSourceIntent.create(qualitative: "Moderate", quantitative: 5, description: "The adversary seeks to obtain or modify specific critical or sensitive information or usurp/disrupt the organization’s cyber resources by establishing a foothold in the organization’s information systems or infrastructure. The adversary is concerned about minimizing attack detection/disclosure of tradecraft, particularly when carrying out attacks over long time periods. The adversary is willing to impede aspects of the organization’s missions/business functions to achieve these ends.")
  AdversarialThreatSourceIntent.create(qualitative: "Low", quantitative: 2, description: "The adversary actively seeks to obtain critical or sensitive information or to usurp/disrupt the organization’s cyber resources, and does so without concern about attack detection/disclosure of tradecraft.")
  AdversarialThreatSourceIntent.create(qualitative: "Very Low", quantitative: 0, description: "The adversary seeks to usurp, disrupt, or deface the organization’s cyber resources, and does so without concern about attack detection/disclosure of tradecraft.")
end

def adversarial_threat_source_targetings
  AdversarialThreatSourceTargeting.create(qualitative: "Very High", quantitative: 10, description: "The adversary analyzes information obtained via reconnaissance and attacks to target persistently a specific organization, enterprise, program, mission or business function, focusing on specific high-value or mission-critical information, resources, supply flows, or functions; specific employees or positions; supporting infrastructure providers/suppliers; or partnering organizations.")
  AdversarialThreatSourceTargeting.create(qualitative: "High", quantitative: 8, description: "The adversary analyzes information obtained via reconnaissance to target persistently a specific organization, enterprise, program, mission or business function, focusing on specific high-value or mission-critical information, resources, supply flows, or functions, specific employees supporting those functions, or key positions.")
  AdversarialThreatSourceTargeting.create(qualitative: "Moderate", quantitative: 5, description: "The adversary analyzes publicly available information to target persistently specific high-value organizations (and key positions, such as Chief Information Officer), programs, or information.")
  AdversarialThreatSourceTargeting.create(qualitative: "Low", quantitative: 2, description: "The adversary uses publicly available information to target a class of high-value organizations or information, and seeks targets of opportunity within that class.")
  AdversarialThreatSourceTargeting.create(qualitative: "Very Low", quantitative: 0, description: "The adversary may or may not target any specific organizations or classes of organizations.")
end

def non_adversarial_threat_source_effects
  NonAdversarialThreatSourceEffect.create(qualitative: "Very High", quantitative: 10, description: "The effects of the error, accident, or act of nature are sweeping, involving almost all of the cyber resources of the [Tier 3: information systems; Tier 2: mission/business processes or EA segments, common infrastructure, or support services; Tier 1: organization/governance structure].")
  NonAdversarialThreatSourceEffect.create(qualitative: "High", quantitative: 8, description: "The effects of the error, accident, or act of nature are extensive, involving most of the cyber resources of the [Tier 3: information systems; Tier 2: mission/business processes or EA segments, common infrastructure, or support services; Tier 1: organization/governance structure], including many critical resources.")
  NonAdversarialThreatSourceEffect.create(qualitative: "Moderate", quantitative: 5, description: "The effects of the error, accident, or act of nature are wide-ranging, involving a significant portion of the cyber resources of the [Tier 3: information systems; Tier 2: mission/business processes or EA segments, common infrastructure, or support services; Tier 1: organization/governance structure], including some critical resources.")
  NonAdversarialThreatSourceEffect.create(qualitative: "Low", quantitative: 2, description: "The effects of the error, accident, or act of nature are limited, involving some of the cyber resources of the [Tier 3: information systems; Tier 2: mission/business processes or EA segments, common infrastructure, or support services; Tier 1: organization/governance structure], but involving no critical resources.")
  NonAdversarialThreatSourceEffect.create(qualitative: "Very Low", quantitative: 0, description: "The effects of the error, accident, or act of nature are minimal, involving few if any of the cyber resources of the [Tier 3: information systems; Tier 2: mission/business processes or EA segments, common infrastructure, or support services; Tier 1: organization/governance structure], and involving no critical resources.")
end

def threat_event_relevances
  ThreatEventRelevance.create(qualitative: "Confirmed", description: "The threat event or TTP has been seen by the organization.")
  ThreatEventRelevance.create(qualitative: "Expected", description: "The threat event or TTP has been seen by the organization’s peers or partners.")
  ThreatEventRelevance.create(qualitative: "Anticipated", description: "The threat event or TTP has been reported by a trusted source.")
  ThreatEventRelevance.create(qualitative: "Predicted", description: "The threat event or TTP has been predicted by a trusted source.")
  ThreatEventRelevance.create(qualitative: "Possible", description: "The threat event or TTP has been described by a somewhat credible source.")
  ThreatEventRelevance.create(qualitative: "N/A", description: "The threat event or TTP is not currently applicable. For example, a threat event or TTP could assume specific technologies, architectures, or processes that are not present in the organization, mission/business process, EA segment, or information system; or predisposing conditions that are not present (e.g., location in a flood plain). Alternately, if the organization is using detailed or specific threat information, a threat event or TTP could be deemed inapplicable because information indicates that no adversary is expected to initiate the threat event or use the TTP.")
end

def vulnerability_severities
  VulnerabilitySeverity.create(qualitative: "Very High", quantitative: 10, description: "The vulnerability is exposed and exploitable, and its exploitation could result in severe impacts.
Relevant security control or other remediation is not implemented and not planned; or no security measure can be identified to remediate the vulnerability.")
  VulnerabilitySeverity.create(qualitative: "High", quantitative: 8, description: "The vulnerability is of high concern, based on the exposure of the vulnerability and ease of exploitation and/or on the severity of impacts that could result from its exploitation.
Relevant security control or other remediation is planned but not implemented; compensating controls are in place and at least minimally effective.")
  VulnerabilitySeverity.create(qualitative: "Moderate", quantitative: 5, description: "The vulnerability is of moderate concern, based on the exposure of the vulnerability and ease of exploitation and/or on the severity of impacts that could result from its exploitation.
Relevant security control or other remediation is partially implemented and somewhat effective.")
  VulnerabilitySeverity.create(qualitative: "Low", quantitative: 2, description: "The vulnerability is of minor concern, but effectiveness of remediation could be improved.
Relevant security control or other remediation is fully implemented and somewhat effective.")
  VulnerabilitySeverity.create(qualitative: "Very Low", quantitative: 0, description: "The vulnerability is not of concern.
Relevant security control or other remediation is fully implemented, assessed, and effective.")
end

def predisposing_conditions
  PredisposingCondition.create(category: "Information-Related", description: "Needs to handle information (as it is created, transmitted, stored, processed, and/or displayed) in a specific manner, due to its sensitivity (or lack of sensitivity), legal or regulatory requirements, and/or contractual or other organizational agreements.")
  PredisposingCondition.create(category: "Technical", description: "Needs to use technologies in specific ways.")
  PredisposingCondition.create(category: "Operational / Environmental", description: "Ability to rely upon physical, procedural, and personnel controls provided by the operational environment.")
end

def predisposing_condition_pervasivenesses
  PredisposingConditionPervasiveness.create(qualitative: "Very High", quantitative: 10, description: "Applies to all organizational missions/business functions (Tier 1), mission/business processes (Tier 2), or information systems (Tier 3).")
  PredisposingConditionPervasiveness.create(qualitative: "High", quantitative: 8, description: "Applies to most organizational missions/business functions (Tier 1), mission/business processes (Tier 2), or information systems (Tier 3).")
  PredisposingConditionPervasiveness.create(qualitative: "Moderate", quantitative: 5, description: "Applies to many organizational missions/business functions (Tier 1), mission/business processes (Tier 2), or information systems (Tier 3).")
  PredisposingConditionPervasiveness.create(qualitative: "Low", quantitative: 2, description: "Applies to some organizational missions/business functions (Tier 1), mission/business processes (Tier 2), or information systems (Tier 3).")
  PredisposingConditionPervasiveness.create(qualitative: "Very Low", quantitative: 0, description: "Applies to few organizational missions/business functions (Tier 1), mission/business processes (Tier 2), or information systems (Tier 3).")
end

def threat_event_initiation_likelihoods
  ThreatEventInitiationLikelihood.create(qualitative: "Very High", quantitative: 10, description: "Adversary is almost certain to initiate the threat event.")
  ThreatEventInitiationLikelihood.create(qualitative: "High", quantitative: 8, description: "Adversary is highly likely to initiate the threat event.")
  ThreatEventInitiationLikelihood.create(qualitative: "Moderate", quantitative: 5, description: "Adversary is somewhat likely to initiate the treat event.")
  ThreatEventInitiationLikelihood.create(qualitative: "Low", quantitative: 2, description: "Adversary is unlikely to initiate the threat event.")
  ThreatEventInitiationLikelihood.create(qualitative: "Very Low", quantitative: 0, description: "Adversary is highly unlikely to initiate the threat event.")
end

def threat_event_occurence_likelihoods
  ThreatEventOccurenceLikelihood.create(qualitative: "Very High", quantitative: 10, description: "Error, accident, or act of nature is almost certain to occur; or occurs more than 100 times a year.")
  ThreatEventOccurenceLikelihood.create(qualitative: "High", quantitative: 8, description: "Error, accident, or act of nature is highly likely to occur; or occurs between 10-100 times a year.")
  ThreatEventOccurenceLikelihood.create(qualitative: "Moderate", quantitative: 5, description: "Error, accident, or act of nature is somewhat likely to occur; or occurs between 1-10 times a year.")
  ThreatEventOccurenceLikelihood.create(qualitative: "Low", quantitative: 2, description: "Error, accident, or act of nature is unlikely to occur; or occurs less than once a year, but more than once every 10 years.")
  ThreatEventOccurenceLikelihood.create(qualitative: "Very Low", quantitative: 0, description: "Error, accident, or act of nature is highly unlikely to occur; or occurs less than once every 10 years.")
end

def threat_event_adverse_impact_likelihoods
  ThreatEventAdverseImpactLikelihood.create(qualitative: "Very High", quantitative: 10, description: "If the threat event is initiated or occurs, it is almost certain to have adverse impacts.")
  ThreatEventAdverseImpactLikelihood.create(qualitative: "High", quantitative: 8, description: "If the threat event is initiated or occurs, it is highly likely to have adverse impacts.")
  ThreatEventAdverseImpactLikelihood.create(qualitative: "Moderate", quantitative: 5, description: "If the threat event is initiated or occurs, it is somewhat likely to have adverse impacts.")
  ThreatEventAdverseImpactLikelihood.create(qualitative: "Low", quantitative: 2, description: "If the threat event is initiated or occurs, it is unlikely to have adverse impacts.")
  ThreatEventAdverseImpactLikelihood.create(qualitative: "Very Low", quantitative: 0, description: "If the threat event is initiated or occurs, it is highly unlikely to have adverse impacts.")
end

def adverse_impacts
  AdverseImpact.create(category: "Harm to Operations", description: "
- Inability to perform current missions/business functions.
- In a sufficiently timely manner.
- With sufficient confidence and/or correctness.
- Within planned resource constraints.
- Inability, or limited ability, to perform missions/business functions in the future.
- Inability to restore missions/business functions.
- In a sufficiently timely manner.
- With sufficient confidence and/or correctness.
- Within planned resource constraints.
- Harms (e.g., financial costs, sanctions) due to noncompliance.
- With applicable laws or regulations.
- With contractual requirements or other requirements in other binding agreements (e.g., liability).
- Direct financial costs.
- Relational harms.
- Damage to trust relationships.
- Damage to image or reputation (and hence future or potential trust relationships).")
  AdverseImpact.create(category: "Harm to Assets", description: "
- Damage to or loss of physical facilities.
- Damage to or loss of information systems or networks.
- Damage to or loss of information technology or equipment.
- Damage to or loss of component parts or supplies.
- Damage to or of loss of information assets.
- Loss of intellectual property.")
  AdverseImpact.create(category: "Harm to Individuals", description: "
- Injury or loss of life.
- Physical or psychological mistreatment.
- Identity theft.
- Loss of Personally Identifiable Information.
- Damage to image or reputation.")
  AdverseImpact.create(category: "Harm to Other Organizations", description: "
- Harms (e.g., financial costs, sanctions) due to noncompliance.
- With applicable laws or regulations.
- With contractual requirements or other requirements in other binding agreements.
- Direct financial costs.
- Relational harms.
- Damage to trust relationships.
- Damage to reputation (and hence future or potential trust relationships).")
  AdverseImpact.create(category: "Harm to the Nation", description: "
- Damage to or incapacitation of a critical infrastructure sector.
- Loss of government continuity of operations.
- Relational harms.
- Damage to trust relationships with other governments or with nongovernmental entities.
- Damage to national reputation (and hence future or potential trust relationships).
- Damage to current or future ability to achieve national objectives.
- Harm to national security.")
end

def threat_event_impacts
  ThreatEventImpact.create(qualitative: "Very High", quantitative: 10, description: "The threat event could be expected to have multiple severe or catastrophic adverse effects on organizational operations, organizational assets, individuals, other organizations, or the Nation.")
  ThreatEventImpact.create(qualitative: "High", quantitative: 8, description: "The threat event could be expected to have a severe or catastrophic adverse effect on organizational operations, organizational assets, individuals, other organizations, or the Nation. A severe or catastrophic adverse effect means that, for example, the threat event might: (i) cause a severe degradation in or loss of mission capability to an extent and duration that the organization is not able to perform one or more of its primary functions; (ii) result in major damage to organizational assets; (iii) result in major financial loss; or (iv) result in severe or catastrophic harm to individuals involving loss of life or serious life-threatening injuries.")
  ThreatEventImpact.create(qualitative: "Moderate", quantitative: 5, description: "The threat event could be expected to have a serious adverse effect on organizational operations, organizational assets, individuals other organizations, or the Nation. A serious adverse effect means that, for example, the threat event might: (i) cause a significant degradation in mission capability to an extent and duration that the organization is able to perform its primary functions, but the effectiveness of the functions is significantly reduced; (ii) result in significant damage to organizational assets; (iii) result in significant financial loss; or (iv) result in significant harm to individuals that does not involve loss of life or serious life-threatening injuries.")
  ThreatEventImpact.create(qualitative: "Low", quantitative: 2, description: "The threat event could be expected to have a limited adverse effect on organizational operations, organizational assets, individuals other organizations, or the Nation. A limited adverse effect means that, for example, the threat event might: (i) cause a degradation in mission capability to an extent and duration that the organization is able to perform its primary functions, but the effectiveness of the functions is noticeably reduced; (ii) result in minor damage to organizational assets; (iii) result in minor financial loss; or (iv) result in minor harm to individuals.")
  ThreatEventImpact.create(qualitative: "Very Low", quantitative: 0, description: "The threat event could be expected to have a negligible adverse effect on organizational operations, organizational assets, individuals other organizations, or the Nation.")
end

def threat_events
  ThreatEvent.create(category: "Perform reconnaissance and gather information.", ttp: "Perform perimeter network reconnaissance/scanning.", description: "Adversary uses commercial or free software to scan organizational perimeters to obtain a better understanding of the information technology infrastructure and improve the ability to launch successful attacks.", is_adversarial: true)
  ThreatEvent.create(category: "Perform reconnaissance and gather information.", ttp: "Perform network sniffing of exposed networks.", description: "Adversary with access to exposed wired or wireless data channels used to transmit information, uses network sniffing to identify components, resources, and protections.", is_adversarial: true)
  ThreatEvent.create(category: "Perform reconnaissance and gather information.", ttp: "Gather information using open source discovery of organizational information.", description: "Adversary mines publically accessible information to gather information about organizational information systems, business processes, users or personnel, or external relationships that the adversary can subsequently employ in support of an attack.", is_adversarial: true)
  ThreatEvent.create(category: "Perform reconnaissance and gather information.", ttp: "Perform reconnaissance and surveillance of targeted organizations.", description: "Adversary uses various means (e.g., scanning, physical observation) over time to examine and assess organizations and ascertain points of vulnerability.", is_adversarial: true)
  ThreatEvent.create(category: "Perform reconnaissance and gather information.", ttp: "Perform malware-directed internal reconnaissance.", description: "Adversary uses malware installed inside the organizational perimeter to identify targets of opportunity. Because the scanning, probing, or observation does not cross the perimeter, it is not detected by externally placed intrusion detection systems.", is_adversarial: true)
  ThreatEvent.create(category: "Craft or create attack tools.", ttp: "Craft phishing attacks.", description: "Adversary counterfeits communications from a legitimate/trustworthy source to acquire sensitive information such as usernames, passwords, or SSNs. Typical attacks occur via email, instant messaging, or comparable means; commonly directing users to websites that appear to be legitimate sites, while actually stealing the entered information.", is_adversarial: true)
  ThreatEvent.create(category: "Craft or create attack tools.", ttp: "Craft spear phishing attacks.", description: "Adversary employs phishing attacks targeted at high value targets (e.g., senior leaders/executives).", is_adversarial: true)
  ThreatEvent.create(category: "Craft or create attack tools.", ttp: "Craft attacks specifically based on deployed information technology environment.", description: "Adversary develops attacks (e.g., crafts targeted malware) that take advantage of adversary knowledge of the organizational information technology environment.", is_adversarial: true)
  ThreatEvent.create(category: "Craft or create attack tools.", ttp: "Create counterfeit/spoof website.", description: "Adversary creates duplicates of legitimate websites; when users visit a counterfeit site, the site can gather information or download malware.", is_adversarial: true)
  ThreatEvent.create(category: "Craft or create attack tools.", ttp: "Craft counterfeit certificates.", description: "Adversary counterfeits or compromises a certificate authority, so that malware or connections will appear legitimate.", is_adversarial: true)
  ThreatEvent.create(category: "Craft or create attack tools.", ttp: "Create and operate false front organizations to inject malicious components into the supply chain.", description: "Adversary creates false front organizations with the appearance of legitimate suppliers in the critical life-cycle path that then inject corrupted/malicious information system components into the organizational supply chain.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Deliver known malware to internal organizational information systems (e.g., virus via email).", description: "Adversary uses common delivery mechanisms (e.g., email) to install/insert known malware (e. g., malware whose existence is known) into organizational information systems.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Deliver modified malware to internal organizational information systems.", description: "Adversary uses more sophisticated delivery mechanisms than email (e.g., web traffic, instant messaging, FTP) to deliver malware and possibly modifications of known malware to gain access to internal organizational information systems.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Deliver targeted malware for control of internal systems and exfiltration of data.", description: "Adversary installs malware that is specifically designed to take control of internal organizational information systems, identify sensitive information, exfiltrate the information back to adversary, and conceal these actions.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Deliver malware by providing removable media.", description: "Adversary places removable media (e.g., flash drives) containing malware in locations external to organizational physical perimeters but where employees are likely to find the media (e.g., facilities parking lots, exhibits at conferences attended by employees) and use it on organizational information systems.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert untargeted malware into downloadable software and/or into commercial information technology products.", description: "Adversary corrupts or inserts malware into common freeware, shareware or commercial information technology products. Adversary is not targeting specific organizations, simply looking for entry points into internal organizational information systems. Note that this is particularly a concern for mobile applications.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert targeted malware into organizational information systems and information system components.", description: "Adversary inserts malware into organizational information systems and information system components (e.g., commercial information technology products), specifically targeted to the hardware, software, and firmware used by organizations (based on knowledge gained via reconnaissance).", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert specialized malware into organizational information systems based on system configurations.", description: "Adversary inserts specialized, non-detectable, malware into organizational information systems based on system configurations, specifically targeting critical information system components based on reconnaissance and placement within organizational information systems.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert counterfeit or tampered hardware into the supply chain.", description: "Adversary intercepts hardware from legitimate suppliers. Adversary modifies the hardware or replaces it with faulty or otherwise modified hardware.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert tampered critical components into organizational systems.", description: "Adversary replaces, though supply chain, subverted insider, or some combination thereof, critical information system components with modified or corrupted components.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Install general-purpose sniffers on organization-controlled information systems or networks.", description: "Adversary installs sniffing software onto internal organizational information systems or networks.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Install persistent and targeted sniffers on organizational information systems and networks.", description: "Adversary places within internal organizational information systems or networks software designed to (over a continuous period of time) collect (sniff) network traffic.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert malicious scanning devices (e.g., wireless sniffers) inside facilities.", description: "Adversary uses postal service or other commercial delivery services to deliver to organizational mailrooms a device that is able to scan wireless communications accessible from within the mailrooms and then wirelessly transmit information back to adversary.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert subverted individuals into organizations.", description: "Adversary places individuals within organizations who are willing and able to carry out actions to cause harm to organizational missions/business functions.", is_adversarial: true)
  ThreatEvent.create(category: "Deliver/insert/install malicious capabilities.", ttp: "Insert subverted individuals into privileged positions in organizations.", description: "Adversary places individuals in privileged positions within organizations who are willing and able to carry out actions to cause harm to organizational missions/business functions. Adversary may target privileged functions to gain access to sensitive information (e.g., user accounts, system files, etc.) and may leverage access to one privileged capability to get to another capability.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit physical access of authorized staff to gain access to organizational facilities.", description: "Adversary follows (“tailgates”) authorized individuals into secure/controlled locations with the goal of gaining access to facilities, circumventing physical security checks.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit poorly configured or unauthorized information systems exposed to the Internet.", description: "Adversary gains access through the Internet to information systems that are not authorized for Internet connectivity or that do not meet organizational configuration requirements.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit split tunneling.", description: "Adversary takes advantage of external organizational or personal information systems (e.g., laptop computers at remote locations) that are simultaneously connected securely to organizational information systems or networks and to nonsecure remote connections.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit multi-tenancy in a cloud environment.", description: "Adversary, with processes running in an organizationally-used cloud environment, takes advantage of multi-tenancy to observe behavior of organizational processes, acquire organizational information, or interfere with the timely or correct functioning of organizational processes.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit known vulnerabilities in mobile systems (e.g., laptops, PDAs, smart phones).", description: "Adversary takes advantage of fact that transportable information systems are outside physical protection of organizations and logical protection of corporate firewalls, and compromises the systems based on known vulnerabilities to gather information from those systems.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit recently discovered vulnerabilities.", description: "Adversary exploits recently discovered vulnerabilities in organizational information systems in an attempt to compromise the systems before mitigation measures are available or in place.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit vulnerabilities on internal organizational information systems.", description: "Adversary searches for known vulnerabilities in organizational internal information systems and exploits those vulnerabilities.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit vulnerabilities using zero-day attacks.", description: "Adversary employs attacks that exploit as yet unpublicized vulnerabilities. Zero-day attacks are based on adversary insight into the information systems and applications used by organizations as well as adversary reconnaissance of organizations.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit vulnerabilities in information systems timed with organizational mission/business operations tempo.", description: "Adversary launches attacks on organizations in a time and manner consistent with organizational needs to conduct mission/business operations.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Exploit insecure or incomplete data deletion in multi-tenant environment.", description: "Adversary obtains unauthorized information due to insecure or incomplete data deletion in a multi-tenant environment (e.g., in a cloud computing environment).", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Violate isolation in multi-tenant environment.", description: "Adversary circumvents or defeats isolation mechanisms in a multi-tenant environment (e.g., in a cloud computing environment) to observe, corrupt, or deny service to hosted services and information/data.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Compromise critical information systems via physical access.", description: "Adversary obtains physical access to organizational information systems and makes modifications.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Compromise information systems or devices used externally and reintroduced into the enterprise.", description: "Adversary installs malware on information systems or devices while the systems/devices are external to organizations for purposes of subsequently infecting organizations when reconnected.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Compromise software of organizational critical information systems.", description: "Adversary inserts malware or otherwise corrupts critical internal organizational information systems.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Compromise organizational information systems to facilitate exfiltration of data/information.", description: "Adversary implants malware into internal organizational information systems, where the malware over time can identify and then exfiltrate valuable information.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Compromise mission-critical information.", description: "Adversary compromises the integrity of mission-critical information, thus preventing or impeding ability of organizations to which information is supplied, from carrying out operations.", is_adversarial: true)
  ThreatEvent.create(category: "Exploit and compromise.", ttp: "Compromise design, manufacture, and/or distribution of information system components (including hardware, software, and firmware).", description: "Adversary compromises the design, manufacture, and/or distribution of critical information system components at selected suppliers.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct communications interception attacks.", description: "Adversary takes advantage of communications that are either unencrypted or use weak encryption (e.g., encryption containing publically known flaws), targets those communications, and gains access to transmitted information and channels.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct wireless jamming attacks.", description: "Adversary takes measures to interfere with wireless communications so as to impede or prevent communications from reaching intended recipients.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct attacks using unauthorized ports, protocols and services.", description: "Adversary conducts attacks using ports, protocols, and services for ingress and egress that are not authorized for use by organizations.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct attacks leveraging traffic/data movement allowed across perimeter.", description: "Adversary makes use of permitted information flows (e.g., email communication, removable storage) to compromise internal information systems, which allows adversary to obtain and exfiltrate sensitive information through perimeters.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct simple Denial of Service (DoS) attack.", description: "Adversary attempts to make an Internet-accessible resource unavailable to intended users, or prevent the resource from functioning efficiently or at all, temporarily or indefinitely.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct Distributed Denial of Service (DDoS) attacks.", description: "Adversary uses multiple compromised information systems to attack a single target, thereby causing denial of service for users of the targeted information systems.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct targeted Denial of Service (DoS) attacks.", description: "Adversary targets DoS attacks to critical information systems, components, or supporting infrastructures, based on adversary knowledge of dependencies.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct physical attacks on organizational facilities.", description: "Adversary conducts a physical attack on organizational facilities (e.g., sets a fire).", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct physical attacks on infrastructures supporting organizational facilities.", description: "Adversary conducts a physical attack on one or more infrastructures supporting organizational facilities (e.g., breaks a water main, cuts a power line).", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct cyber-physical attacks on organizational facilities.", description: "Adversary conducts a cyber-physical attack on organizational facilities (e.g., remotely changes HVAC settings).", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct data scavenging attacks in a cloud environment.", description: "Adversary obtains data used and then deleted by organizational processes running in a cloud environment.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct brute force login attempts/password guessing attacks.", description: "Adversary attempts to gain access to organizational information systems by random or systematic guessing of passwords, possibly supported by password cracking utilities.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct nontargeted zero-day attacks.", description: "Adversary employs attacks that exploit as yet unpublicized vulnerabilities. Attacks are not based on any adversary insights into specific vulnerabilities of organizations.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct externally-based session hijacking.", description: "Adversary takes control of (hijacks) already established, legitimate information system sessions between organizations and external entities (e.g., users connecting from off-site locations).", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct internally-based session hijacking.", description: "Adversary places an entity within organizations in order to gain access to organizational information systems or networks for the express purpose of taking control (hijacking) an already established, legitimate session either between organizations and external entities (e.g., users connecting from remote locations) or between two locations within internal networks.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct externally-based network traffic modification (man in the middle) attacks.", description: "Adversary, operating outside organizational systems, intercepts/eavesdrops on sessions between organizational and external systems. Adversary then relays messages between organizational and external systems, making them believe that they are talking directly to each other over a private connection, when in fact the entire communication is controlled by the adversary. Such attacks are of particular concern for organizational use of community, hybrid, and public clouds.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct internally-based network traffic modification (man in the middle) attacks.", description: "Adversary operating within the organizational infrastructure intercepts and corrupts data sessions.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct outsider-based social engineering to obtain information.", description: "Externally placed adversary takes actions (e.g., using email, phone) with the intent of persuading or otherwise tricking individuals within organizations into revealing critical/sensitive information (e.g., personally identifiable information).", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct insider-based social engineering to obtain information.", description: "Internally placed adversary takes actions (e.g., using email, phone) so that individuals within organizations reveal critical/sensitive information (e.g., mission information).", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct attacks targeting and compromising personal devices of critical employees.", description: "Adversary targets key organizational employees by placing malware on their personally owned information systems and devices (e.g., laptop/notebook computers, personal digital assistants, smart phones). The intent is to take advantage of any instances where employees use personal information systems or devices to handle critical/sensitive information.", is_adversarial: true)
  ThreatEvent.create(category: "Conduct an attack (i.e., direct/coordinate attack tools or activities).", ttp: "Conduct supply chain attacks targeting and exploiting critical hardware, software, or firmware.", description: "Adversary targets and compromises the operation of software (e.g., through malware injections), firmware, and hardware that performs critical functions for organizations. This is largely accomplished as supply chain attacks on both commercial off-the-shelf and custom information systems and components.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Obtain sensitive information through network sniffing of external networks.", description: "Adversary with access to exposed wired or wireless data channels that organizations (or organizational personnel) use to transmit information (e.g., kiosks, public wireless networks) intercepts communications.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Obtain sensitive information via exfiltration.", description: "Adversary directs malware on organizational systems to locate and surreptitiously transmit sensitive information.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Cause degradation or denial of attacker-selected services or capabilities.", description: "Adversary directs malware on organizational systems to impair the correct and timely support of organizational mission/business functions.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Cause deterioration/destruction of critical information system components and functions.", description: "Adversary destroys or causes deterioration of critical information system components to impede or eliminate organizational ability to carry out missions or business functions. Detection of this action is not a concern.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Cause integrity loss by creating, deleting, and/or modifying data on publicly accessible information systems (e.g., web defacement).", description: "Adversary vandalizes, or otherwise makes unauthorized changes to, organizational websites or data on websites.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Cause integrity loss by polluting or corrupting critical data.", description: "Adversary implants corrupted and incorrect data in critical data, resulting in suboptimal actions or loss of confidence in organizational data/services.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Cause integrity loss by injecting false but believable data into organizational information systems.", description: "Adversary injects false but believable data into organizational information systems, resulting in suboptimal actions or loss of confidence in organizational data/services.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Cause disclosure of critical and/or sensitive information by authorized users.", description: "Adversary induces (e.g., via social engineering) authorized users to inadvertently expose, disclose, or mishandle critical/sensitive information.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Cause unauthorized disclosure and/or unavailability by spilling sensitive information.", description: "Adversary contaminates organizational information systems (including devices and networks) by causing them to handle information of a classification/sensitivity for which they have not been authorized. The information is exposed to individuals who are not authorized access to such information, and the information system, device, or network is unavailable while the spill is investigated and mitigated.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Obtain information by externally located interception of wireless network traffic.", description: "Adversary intercepts organizational communications over wireless networks. Examples include targeting public wireless access or hotel networking connections, and drive-by subversion of home or organizational wireless routers.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Obtain unauthorized access.", description: "Adversary with authorized access to organizational information systems, gains access to resources that exceeds authorization.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Obtain sensitive data/information from publicly accessible information systems.", description: "Adversary scans or mines information on publically accessible servers and web pages of organizations with the intent of finding sensitive information.", is_adversarial: true)
  ThreatEvent.create(category: "Achieve results (i.e., cause adverse impacts, obtain information)", ttp: "Obtain information by opportunistically stealing or scavenging information systems/components.", description: "Adversary steals information systems or components (e. g., laptop computers or data storage media) that are left unattended outside of the physical perimeters of organizations, or scavenges discarded components.", is_adversarial: true)
  ThreatEvent.create(category: "Maintain a presence or set of capabilities.", ttp: "Obfuscate adversary actions.", description: "Adversary takes actions to inhibit the effectiveness of the intrusion detection systems or auditing capabilities within organizations.", is_adversarial: true)
  ThreatEvent.create(category: "Maintain a presence or set of capabilities.", ttp: "Adapt cyber attacks based on detailed surveillance.", description: "Adversary adapts behavior in response to surveillance and organizational security measures.", is_adversarial: true)
  ThreatEvent.create(category: "Coordinate a campaign.", ttp: "Coordinate a campaign of multi-staged attacks (e.g., hopping).", description: "Adversary moves the source of malicious commands or actions from one compromised information system to another, making analysis difficult.", is_adversarial: true)
  ThreatEvent.create(category: "Coordinate a campaign.", ttp: "Coordinate a campaign that combines internal and external attacks across multiple information systems and information technologies.", description: "Adversary combines attacks that require both physical presence within organizational facilities and cyber methods to achieve success. Physical attack steps may be as simple as convincing maintenance personnel to leave doors or cabinets open.", is_adversarial: true)
  ThreatEvent.create(category: "Coordinate a campaign.", ttp: "Coordinate campaigns across multiple organizations to acquire specific information or achieve desired outcome.", description: "Adversary does not limit planning to the targeting of one organization. Adversary observes multiple organizations to acquire necessary information on targets of interest.", is_adversarial: true)
  ThreatEvent.create(category: "Coordinate a campaign.", ttp: "Coordinate a campaign that spreads attacks across organizational systems from existing presence.", description: "Adversary uses existing presence within organizational systems to extend the adversary’s span of control to other organizational systems including organizational infrastructure. Adversary thus is in position to further undermine organizational ability to carry out missions/business functions.", is_adversarial: true)
  ThreatEvent.create(category: "Coordinate a campaign.", ttp: "Coordinate a campaign of continuous, adaptive, and changing cyber attacks based on detailed surveillance.", description: "Adversary attacks continually change in response to surveillance and organizational security measures.", is_adversarial: true)
  ThreatEvent.create(category: "Coordinate a campaign.", ttp: "Coordinate cyber attacks using external (outsider), internal (insider), and supply chain (supplier) attack vectors.", description: "Adversary employs continuous, coordinated attacks, potentially using all three attack vectors for the purpose of impeding organizational operations.", is_adversarial: true)
  ThreatEvent.create(category: "Spill sensitive information", ttp: "Spill sensitive information", description: "Authorized user erroneously contaminates a device, information system, or network by placing on it or sending to it information of a classification/sensitivity which it has not been authorized to handle. The information is exposed to access by unauthorized individuals, and as a result, the device, system, or network is unavailable while the spill is investigated and mitigated.", is_adversarial: false)
  ThreatEvent.create(category: "Mishandling of critical and/or sensitive information by authorized users", ttp: "Mishandling of critical and/or sensitive information by authorized users", description: "Authorized privileged user inadvertently exposes critical/sensitive information.", is_adversarial: false)
  ThreatEvent.create(category: "Incorrect privilege settings", ttp: "Incorrect privilege settings", description: "Authorized privileged user or administrator erroneously assigns a user exceptional privileges or sets privilege requirements on a resource too low.", is_adversarial: false)
  ThreatEvent.create(category: "Communications contention", ttp: "Communications contention", description: "Degraded communications performance due to contention.", is_adversarial: false)
  ThreatEvent.create(category: "Unreadable display", ttp: "Unreadable display", description: "Display unreadable due to aging equipment.", is_adversarial: false)
  ThreatEvent.create(category: "Earthquake at primary facility", ttp: "Earthquake at primary facility", description: "Earthquake of organization-defined magnitude at primary facility makes facility inoperable.", is_adversarial: false)
  ThreatEvent.create(category: "Fire at primary facility", ttp: "Fire at primary facility", description: "Fire (not due to adversarial activity) at primary facility makes facility inoperable.", is_adversarial: false)
  ThreatEvent.create(category: "Fire at backup facility", ttp: "Fire at backup facility", description: "Fire (not due to adversarial activity) at backup facility makes facility inoperable or destroys backups of software, configurations, data, and/or logs.", is_adversarial: false)
  ThreatEvent.create(category: "Flood at primary facility", ttp: "Flood at primary facility", description: "Flood (not due to adversarial activity) at primary facility makes facility inoperable.", is_adversarial: false)
  ThreatEvent.create(category: "Flood at backup facility", ttp: "Flood at backup facility", description: "Flood (not due to adversarial activity) at backup facility makes facility inoperable or destroys backups of software, configurations, data, and/or logs.", is_adversarial: false)
  ThreatEvent.create(category: "Hurricane at primary facility", ttp: "Hurricane at primary facility", description: "Hurricane of organization-defined strength at primary facility makes facility inoperable.", is_adversarial: false)
  ThreatEvent.create(category: "Hurricane at backup facility", ttp: "Hurricane at backup facility", description: "Hurricane of organization-defined strength at backup facility makes facility inoperable or destroys backups of software, configurations, data, and/or logs.", is_adversarial: false)
  ThreatEvent.create(category: "Resource depletion", ttp: "Resource depletion", description: "Degraded processing performance due to resource depletion.", is_adversarial: false)
  ThreatEvent.create(category: "Introduction of vulnerabilities into software products", ttp: "Introduction of vulnerabilities into software products", description: "Due to inherent weaknesses in programming languages and software development environments, errors and vulnerabilities are introduced into commonly used software products.", is_adversarial: false)
  ThreatEvent.create(category: "Disk error", ttp: "Disk error", description: "Corrupted storage due to a disk error.", is_adversarial: false)
  ThreatEvent.create(category: "Pervasive disk error", ttp: "Pervasive disk error", description: "Multiple disk errors due to aging of a set of devices all acquired at the same time, from the same supplier.", is_adversarial: false)
  ThreatEvent.create(category: "Windstorm/tornado at primary facility", ttp: "Windstorm/tornado at primary facility", description: "Windstorm/tornado of organization-defined strength at primary facility makes facility inoperable.", is_adversarial: false)
  ThreatEvent.create(category: "Windstorm/tornado at backup facility", ttp: "Windstorm/tornado at backup facility", description: "Windstorm/tornado of organization-defined strength at backup facility makes facility inoperable or destroys backups of software, configurations, data, and/or logs.", is_adversarial: false)
end

# Load up seeds selectively.
threat_sources
adversarial_threat_source_capabilities
adversarial_threat_source_intents
adversarial_threat_source_targetings
non_adversarial_threat_source_effects
threat_event_relevances
vulnerability_severities
predisposing_conditions
predisposing_condition_pervasivenesses
threat_event_initiation_likelihoods
threat_event_occurence_likelihoods
threat_event_adverse_impact_likelihoods
adverse_impacts
threat_event_impacts
threat_events